name: videostore_api
description: Custom videostore grpc API
version: 0.0.0
homepage: https://github.com/viam-modules/viamrtsp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.1
  protobuf: ^3.0.0
  connectrpc: ^1.0.0
  viam_sdk: ^0.10.0

# dependency_overrides:
#   protobuf: ^4.2.0